// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChannelList: typeof import('./src/components/ChannelList.vue')['default']
    ChannelRow: typeof import('./src/components/ChannelRow.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    MessageEmbed: typeof import('./src/components/MessageEmbed.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MessageRow: typeof import('./src/components/MessageRow.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NElement: typeof import('naive-ui')['NElement']
    NewTopicModal: typeof import('./src/components/NewTopicModal.vue')['default']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMention: typeof import('naive-ui')['NMention']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OTPForm: typeof import('./src/components/OTPForm.vue')['default']
    PhoneForm: typeof import('./src/components/PhoneForm.vue')['default']
    Row: typeof import('./src/components/Row.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    TopicList: typeof import('./src/components/TopicList.vue')['default']
    TopicRow: typeof import('./src/components/TopicRow.vue')['default']
    Vote: typeof import('./src/components/Vote.vue')['default']
  }
}

export { }
